---
version: 2

updates:
  - package-ecosystem: github-actions

    commit-message:
      prefix: ci

    directory: /

    schedule:
      interval: daily

  - package-ecosystem: devcontainers

    directory: /

    schedule:
      interval: weekly
